- .github/workflows/ci.yml
- CODE_OF_CONDUCT.rst
- CONTRIBUTING.rst
- LICENSE
- README.rst
- tests/unit/cli/admin/test_ceremony.py
- Rename giving the new github organization
- Add some development docs and Licensing
- Update the CI/CD
> Renaming, docs and CI/CD

- repository_service_tuf/cli/__init__.py
- tests/test_tuf_repository_service.py
- We added the parameter ```--version``` that shows the ```rstuf``` version.
- Added a check to make sure that the --version parameter exists and that it has the specified
standard output format.
Closes #70
Signed-off-by: Konstantinos Papadopoulos <konpap1996@yahoo.com>
> Add parameter for CLI to show version

- .github/workflows/ci.yml
The tests must run in the push to main branch.
It will send to codecov the current stats to the main branch.
> Fix codecov stats for main branch

- Makefile
- tox.ini
Fixes #72
The changes in this pr are as follows:
1. update the `pipenv` command in `Makefile`
2. add a tox ci test where we check if there is a new dependency or version of a dependency that should be added to any of the requirements files.
PS: These changes in this pr were first discussed here: https://github.com/vmware/repository-service-tuf-api/pull/124
> Update pipenv commands and add requirements tox run

- tox.ini
Fixes: #86
Add "requirements" in the tox.in envlist.
> Add "requirements" in the tox.in envlist

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Pin hashes for GitHub actions in workflow yml files.
This will allow dependabot to update our actions by using hashes
as well.
I checked the latest stable versions for each of our action dependencies and got the commit hashes.
I have done a check for security advisories for each of the actions, but haven't found any.
The versions I have used for each of the actions are as follows:
- [actions/checkout v3.1.0](https://github.com/actions/checkout/releases/tag/v3.1.0)
- [actions/setup-python v4.3.0](https://github.com/actions/setup-python/releases/tag/v4.3.0)
- [codecov/codecov-action v3.1.1](https://github.com/codecov/codecov-action/releases/tag/v3.1.1)
> Pin hashes for GitHub actions in workflow ci file

- .github/workflows/update-python-deps.yml
- tox.ini
The following PR adds a dedicated workflow for updating Python dependencies.
Details:
* Runs daily
* If another one is already opened, it doesn't create a new one, instead, it updates it.
Related to https://github.com/vmware/repository-service-tuf/issues/84
Signed-off-by: Radoslav Dimitrov <dimitrovr@vmware.com>
> build: add workflow for updating python dependencies

- repository_service_tuf/cli/admin/ceremony.py
The _key_is_duplicated() function now accepts the
"roles_keys_input_list: ValuesView[RoleSettingsInput]" argument which seems complicated.
Instead of using ValuesView as a type, we can instead use "list" as a type as the only place, where we use the "roles_keys_input_list", is as a list. Also, the name "roles_keys_input_list" suggests the type should be a list.
Additionally, try to give a better name than "roles_keys_input_list".
> Simplify _key_is_duplicated() argument

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/other.yml
- .github/ISSUE_TEMPLATE/task.yml
- .github/PULL_REQUEST_TEMPLATE/pr.yml
The following PR adds templates for both issues and pull requests.
It is based on the beta feature of Github to use yml issue forms which contribute to a better user experience - ref. [github/creating-issue-forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
Signed-off-by: Radoslav Dimitrov <dimitrovr@vmware.com>
> chore: add github templates for issues and PRs

- pyproject.toml
In pyproject.toml we should depend on dynaconf[ini] instead of only dynaconf in order to install the 
"configobj" file together with dynaconf.
Close #119
> Fix Dynaconf[ini] dependency in pyproject.toml

- .github/workflows/cd.yml
When a release is trigged, it uses the functional tests from vmware/repository-service-tuf (umbrella repository).
The release is build/published if the functional tests is ok
Closes #116
> build: functional tests before release

- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/helpers/tuf.py
- tests/conftest.py
- tests/unit/cli/admin/test_ceremony.py
The following PR reverts commit b2afa4688fb646dbbd56f8e98767cbc70ca7a092, because it introduces an incompatible payload with `rstuf-api`.
**Reproduce:**
* Deploy rstuf
* Use the latest CLI
* Perform the ceremony online OR generate a payload with the CLI offline and upload it
**Impacts:**
* repository-service-tuf-cli >= [v0.0.1a4](https://github.com/vmware/repository-service-tuf-cli/releases/tag/v0.0.1a4) 
**Reference:** 
```
Configuration correct for bins? [y/n]: y
╭─ Error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```
> Revert "Dev/add UT for ceremony._key_is_duplicated (#88)"

- repository_service_tuf/cli/admin/ceremony.py
- tests/unit/cli/admin/test_ceremony.py
This will save the metadata during the UT for bootstrap.
This data can be reused in other tests such as FT
> tests: save metadata when generate the default

- CONTRIBUTING.rst
- README.rst
In general, in this PR we want to focus on the
restructuring of the README and CONTRIBUTING
files and not as much on their content.
This structure can be used similarly for the
other RSTUF projects.
This is an initial structure that will evolve and of
course it's just a suggestion to get started with,
please leave your feedback.
Implementation details:
- Moved the Development section of the README.rst to the CONTRIBUTING.rst as a new section and
adjusted it
- Added short Installation, Usage and License sections to the README.rst
- Fixed minor typos and made small improvements
Closes #124
> Refactor contribution content in README and CONTRIBUTING files

- Pipfile
- Pipfile.lock
- pyproject.toml
- requirements-dev.txt
- requirements.txt
The `cryptography` package is a dependency of the `securesystemslib` package, to be exact it is an _optional_ dependency. `securesystemslib` uses "optional dependencies" ("extras") to allow a default installation with limited capabilities.
However, since we are making use of the `cryptography` library via `securesystemslib`, we need to install at least the `crypto` extra.
With my PR fix I don't see this error, but following the same steps as above I get:
```shell
❌ Failed: Invalid encrypted file. Check the password.
```
This might have to do with my key however, can someone verify the fix from their side?
Fixes #131
Signed-off-by: Konstantinos Papadopoulos <konpap1996@yahoo.com>
> Add `crypto` extra to the `securesystemslib` requirement

- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- repository_service_tuf/helpers/api_client.py
- repository_service_tuf/helpers/tuf.py
- requirements-dev.txt
- requirements.txt
- tox.ini
To achieve the OpenSSF Best Practices badge, we need to implement
the static code analysis tool.
This commit adds the `bandit` to the RSTUF CLI.
> Add bandit pre commit

- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- pyproject.toml
- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/helpers/tuf.py
- requirements-dev.txt
- requirements.txt
- tox.ini
Adding a bit of context below since this PR addresses quite a few typing issues.
- In the `_update_snapshot` function we encounter the following typing error: `repository_service_tuf/helpers/tuf.py:195: error: Value of type variable "T" of "Metadata" cannot be "Signed"  [type-var]`. I have ignored it for now, if we can't find a solution in the scope of this PR I suggest opening a new issue to track it, so that we don't block the merging of this PR.
- For errors of the type:
`error: Skipping analyzing <module_name>: module is installed, but missing library stubs or py.typed marker  [import]`, there are basically 4 possible options, see https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker:
1. _Upgrading the version of the library you’re using, in …
> Reintroduce mypy checks

- Pipfile
- Pipfile.lock
- docs/source/guide/index.rst
- pyproject.toml
- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/cli/admin/import_targets.py
- repository_service_tuf/helpers/api_client.py
- requirements-dev.txt
- requirements.txt
- tests/unit/cli/admin/test_ceremony.py
- tests/unit/cli/admin/test_import_targets.py
- tests/unit/helpers/test_api_client.py
- tox.ini
Implements the feature import target `rstuf admin import-targets`.
This feature gives the RSTUF administrator the functionality to import a large number of existent targets. It helps to roll out and deploy the RSTUF in existing repositories.
This feature is detailed and explained at these links
- https://github.com/vmware/repository-service-tuf/issues/188
- BDD Feature: https://github.com/vmware/repository-service-tuf/pull/218
Some changes in the ceremony was done to reuse in the code:
- The `ceremony._check_server` was converted to `helpers.api_client.get_headers`
- The `ceremony._bootstrap_state` was converted to `helpers.api_client.task_status`
Added 100% coverage to `helpsers.api_client`
> feature: import targets

- repository_service_tuf/cli/admin/import_targets.py
- tests/unit/cli/admin/test_import_targets.py
We have made "sqlalchemy" an optional dependency only for users who want to use the "import-targets" CLI command.
The reason for that is that we expect that this command will be rarely used.
For that reason, "sqlalchemy" is not installed by default, but we import all modules within the "repository_service_tuf/cli/admin" folder and given we imported "sqlalchemy" globally in import_targets module this resulted in an error "ModuleNotFoundError: No module 'sqlalchemy".
To resolve this issue we decided to import "sqlalchemy" inside the import_targets() function so that only when the "import-targets" command is used then you would see you will possibly get this error.
Closes https://github.com/vmware/repository-service-tuf/issues/245
> Fix ModuleNotFoundError: No module 'sqlalchemy'

- docs/source/guide/index.rst
This is to be used by documentation in Guide.
It doesn't add extra docs for users.
- Used by https://github.com/vmware/repository-service-tuf/pull/254
> Add marks for including accross docs

- docs/source/guide/index.rst
- repository_service_tuf/cli/admin/ceremony.py
The CLI Guide is outdated after the new flow for adding the single online key.
This commit updates it.
Basically, it is a new copy from the CLI interface.
In some of `.. code::` the `shell` statement was removed due to incompatibility (special characters in the interface)
Closes #223
> Update CLI Guide with new user flow

- tests/unit/cli/admin/test_ceremony.py
We use this specific test in the Functional Tests.
During the roles-simplification we removed the parameter `--save` (to save the metadata) by mistake.
This commit adds back the parameter to the specific test.
> Add `--save` back to default values test

- docs/source/devel/index.rst
- docs/source/devel/repository_service_tuf.cli.key.rst
- docs/source/guide/index.rst
- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/cli/key/__init__.py
- repository_service_tuf/cli/key/generate_key.py
- repository_service_tuf/constants.py
- tests/unit/cli/admin/test_ceremony.py
- tests/unit/cli/key/test_generate_key.py
This newly added command is used to generate cryptographic keys using the `securesystemslib` library.
Notes:
- We probably still need to create a documentation task for this new CLI command
Closes #219
> Add simple cli key generator

- docs/source/guide/index.rst
I noticed that the correct usage for the anchors is before the titles rather than after.
It will make the documentation more precise to use import `start-after` and `end-before`.
> fix the documentation anchor position

- repository_service_tuf/cli/__init__.py
- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/cli/admin/import_targets.py
- repository_service_tuf/cli/admin/login.py
- repository_service_tuf/cli/admin/token.py
- repository_service_tuf/helpers/api_client.py
- tests/conftest.py
- tests/unit/cli/admin/test_login.py
- tests/unit/cli/test__init__.py
- tests/unit/helpers/test_api_client.py
This adds the `rstuf --no-auth` parameter.
This parameter skips authentication checks/routines when communicating with RSTUF API. This makes RSTUF CLI compatible when the user disables RSTUF API built-in authentication.
Added a small refactoring about using the rich console and shared calls in the helper.
Added refactoring for the CLI init test file.
Closes #251
> Add parameter `--no-auth` to the CLI

- docs/source/guide/index.rst
- repository_service_tuf/cli/admin/ceremony.py
- tests/unit/cli/admin/test_ceremony.py
fix: option --no-auth breaking --upload with auth
This fixes the logic behind `--no-auth` and `--upload` requiring
`--upload-server`.
When the user doesn't use `--no-auth`, but uses `--upload` the current
logic was overwitting the server defined by `rstuf admin login`.
Added tests to prevent regression
> fix: option --no-auth breaking --upload with auth

- repository_service_tuf/cli/admin/token.py
This commit fixes the token usage of `is_logged` helper function. This function was refactored in previous release.
> fix token generation

- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.rst
- README.rst
- tests/unit/cli/admin/test_ceremony.py
It is part of the process moving RSTUF to OpenSSF organization.
> Move RSTUF to github.com/repository-service-tuf

- .github/workflows/cd.yml
The process of publishing the package to PyPI will now be automated.
TODO: Replace secret's name with the repo's one for PyPI (in -> Security -> Secrets and variables -> Actions)
Note: If we want we can test this first before merging by releasing to TestPyPI (will need a new token with project scope).
Closes #238
> Add PyPI publishing in GH workflow

- docs/source/guide/index.rst
- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/helpers/tuf.py
- tests/conftest.py
- tests/unit/cli/admin/test_ceremony.py
- tests/unit/helpers/test_tuf.py
Add a question asking the user if he wants to provide a name for his key.
This will be useful when showing information about roles later during the validation phase.
It will be also useful when showing the keys information during metadata update.
Additionally, I noticed that if I make BootstrapSetup.root_keys as a dict instead of a list this could 
simplify some of our existing functions and a new one that I added when asking for key names.
This feature will be used in my pr for #232 and it's good if we merge it before merging the solution for #232.
> Bootstrap: add key names option and do a small refactor

- .github/workflows/ci.yml
- .github/workflows/update-python-deps.yml
- CONTRIBUTING.rst
- Pipfile
- Pipfile.lock
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- tox.ini
Update Python support to Python >= 3.9 due compatiblity
```log
tox: typing
typing: commands[0]> mypy --exclude tests/ .
repository_service_tuf/helpers/tuf.py:145: error: "dict" is not subscriptable, use "typing.Dict" instead  [misc]
repository_service_tuf/helpers/tuf.py:182: error: "dict" is not subscriptable, use "typing.Dict" instead  [misc]
Found 2 errors in 1 file (checked 14 source files)
typing: exit 1 (20.49 seconds) /home/runner/work/repository-service-tuf-cli/repository-service-tuf-cli> mypy --exclude tests/ . pid=2603
typing: FAIL ✖ in 39.74 seconds
tox: test
test: commands[0]> coverage run '--omit=tests/*' -m pytest -vv
ImportError while loading conftest '/home/runner/work/repository-service-tuf-cli/repository-service-tuf-cli/tests/conftest.py'.
tests/conftest.py:13: in …
```
> Change Python compatibility to >= 3.9

- .pre-commit-config.yaml
- tox.ini
See similar PR: https://github.com/repository-service-tuf/repository-service-tuf-api/pull/286
- Removed the "exclude" settings of `flake8` from `tox.ini` because they were overiding the
ones in `.pre-commit-config.yaml`
- Redefined the files/dirs to be excluded for `flake8` in `.pre-commit-config.yaml`. Specifically:
- took into account that the patterns for `exclude` are python regular expressions and are matched with `re.search`, and not globals as for `tox`. (see https://pre-commit.com/#regular-expressions)
- `pre-commit` won’t ever pass untracked files to `flake8` so excluding files that are in `.gitignore` is unecessary (e.g., `.venv`, `venv`, `.tox`, etc.). See https://flake8.pycqa.org/en/latest/user/using-hooks.html#usage-with-the-pre-commit-git-hooks-framework
> Adapt `flake8` exclude configs to pre-commit

- docs/source/guide/index.rst
- repository_service_tuf/cli/admin/login.py
- tests/unit/cli/admin/test_login.py
Remove username prompt from `rstuf admin login`
RSTUF has a unique username, `admin`, and uses it for a simple auth in the RSTUF API. We simplify it by removing the username prompt.
Closes #242
> Remove username prompt `rstuf admin login`

- Pipfile.lock
- repository_service_tuf/cli/admin/import_targets.py
- repository_service_tuf/helpers/api_client.py
- requirements-dev.txt
- requirements.txt
- tests/unit/cli/admin/test_import_targets.py
This commit fixes the bug on `rstuf admin import-targets`, which wasn't working with RSTUF Worker/API beta version.
The problem is due to the changes in database models for RSTUF Workers.
It also simplifies the way to retrieve the succinct roles.
Closes #297
> Fix import targets and simplify succinct roles

- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/cli/admin/token.py
- repository_service_tuf/helpers/api_client.py
- tests/unit/cli/admin/test_ceremony.py
- tests/unit/helpers/test_api_client.py
The RSTUF CLI was with incorrect behavior during the bootstrap process.
When the user was using `--auth` it was still requiring the `--upload-server` parameter, even after the login procedure `rstuf --auth admin login`
Also, when using the CLI without the authn/z, it was not asking the user the required `--upload-server` parameter.
This commit fixes the correct behavior
```
❯ rstuf --auth admin login
❯ rstuf --auth admin ceremony -b -u
❯ rstuf admin ceremony -b -u
╭─ Error ────────────────────────────────────────────────────────────────────────────╮
│ Requires '--upload-server' Example: --upload-server https://rstuf-api.example.com  │
╰────────────────────────────────────────────────────────────────────────────────────╯
❯ rstuf admin ceremony -b -u --upload-server http://127.0.0.1
``` …
> Fix rstuf admin ceremony -b -u behaviour

- .gitignore
Add `metadata-update-payload.json` to `.gitignore` to not generate new files during github workflows
> Add metadata-update-payload.json to .gitignore

- Pipfile
- Pipfile.lock
- pyproject.toml
- repository_service_tuf/helpers/tuf.py
- requirements-dev.txt
- requirements.txt
- tests/conftest.py
- tests/unit/helpers/test_tuf.py
- Updated `python-tuf` to version 3.0.0 
- Updated all requirements
- Based on https://github.com/theupdateframework/python-tuf/blob/v3.0.0/docs/CHANGELOG.md, the change that would
break `rstuf` is `Key.from_securesystemslib_key()` being removed.
Thus, it was replaced in the code with Securesystemslibs `SSlibKey.from_securesystemslib_key()` as suggested.
- Adjusted tests
Closes #327
> Update python tuf version to 3.0.0

- CONTRIBUTING.rst
- docs/source/guide/index.rst
This change adds missing steps and prereqs in the contributing
documentation and fixes the `rstuf admin login` command in docs with the
missing `--auth` flag
Fixes #379 and #380
- [n/a] Bug fix (non-breaking change which fixes an issue)
- [n/a] New feature (non-breaking change which adds functionality)
- [n/a] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [n/a] Tests have been added for the bug fix or new feature
> Improve Getting Started instructions for development

- README.rst
> Remove warning from README

- repository_service_tuf/cli/admin/metadata.py
- repository_service_tuf/helpers/tuf.py
- tests/conftest.py
- tests/unit/cli/admin/test_metadata.py
- tests/unit/helpers/test_tuf.py
The current implementation of rstuf admin metadata sign asks to choose the Role to sign, select the key available to sign, and sign it.
The user doesn't have a metadata role overview. It would be interesting to show the following:
- Number of keys
- Threshold
- Current signatures and keys
- Show pending signatures
Fixes #349
> Print metadata role for signing and fix api_url arg

- repository_service_tuf/cli/admin/metadata.py
- repository_service_tuf/helpers/api_client.py
- tests/unit/cli/admin/test_metadata.py
- tests/unit/helpers/test_api_client.py
This change allows deleting a signing process with `rstuf admin metadata sign --delete` with an input - a role whoose signate should be deleted and DAS signing process - terminated
Fixes #370
- [tbd ] Docs have been added for the bug fix or new feature
> Add delete option for metadata sign

- repository_service_tuf/cli/admin/metadata.py
- repository_service_tuf/helpers/api_client.py
- tests/unit/cli/admin/test_metadata.py
This change updates the `rstuf admin metadata sign --delete`
command to use `POST api/v1/metadata/sign/delete` instead of 
the previuos `DELETE api/v1/metadata/sign` API
Fixes #409
- [n/a ] Docs have been added for the bug fix or new feature
> Update `sign --delete` to the new API method and path

- repository_service_tuf/cli/admin/metadata.py
- tests/unit/cli/admin/test_metadata.py
This change fixes a potential bug in the `--delete` flag following
from the API method change from DELETE to POST, which
makes the initial approach non-optimal
Fixes #409
- [n/a] Docs have been added for the bug fix or new feature
> Fix `rstuf admin metadata sign --delete`

- Pipfile
- Pipfile.lock
- docs/source/devel/design.rst
- docs/source/guide/index.rst
- repository_service_tuf/cli/__init__.py
- requirements-dev.txt
- requirements.txt
- tests/conftest.py
As `.ini` is recomended mainly for legacy, while `yaml` fomat has many benefits (can convert to json, allows more complex configuration and is the recomended format for Django) this change migrates the config to use yaml
Fixes #332
- [n/a ] Tests have been added for the bug fix or new feature
> Change .ini config to .yaml/.yml

- docs/source/devel/repository_service_tuf.cli.admin.rst
- docs/source/guide/index.rst
- pyproject.toml
- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/cli/admin/import_artifacts.py
- repository_service_tuf/helpers/api_client.py
- tests/unit/cli/admin/test_import_artifacts.py
- tests/unit/helpers/test_api_client.py
- Updates the user commands to show as `import-artifacts` instead `import-targets` following the changes in the API and documentation.
> Refactor: `import-targets` to `import-artifacts`

- .pre-commit-config.yaml
- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/cli/key/generate.py
- repository_service_tuf/constants.py
- repository_service_tuf/helpers/tuf.py
- tests/unit/cli/admin/test_ceremony.py
- tests/unit/cli/key/test_generate.py
- tests/unit/cli/key/test_info.py
When describing a public key during bootstrap the administrators will
now have to describe the public key scheme as well.
For that reason, I have also updated the "rstuf key info" command and
now it gives information about key scheme as well.
Also, fixed test answers to public key questions.
PS: I have added a new test `test_ceremony_online_key_non_ed25519_key_type`
which is described strangely by git as a change of an existing case instead.
I recommend reading both tests to understand what I did.
**Important**: This pr is a requirement for https://github.com/repository-service-tuf/repository-service-tuf-worker/issues
Fixes #428
> Add the choice of a key scheme as a requirement when describing a public key

- docs/source/guide/index.rst
- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/cli/admin/metadata.py
- repository_service_tuf/cli/key/info.py
- repository_service_tuf/helpers/tuf.py
- tests/conftest.py
- tests/unit/cli/admin/test_ceremony.py
- tests/unit/cli/admin/test_metadata.py
- tests/unit/cli/key/test_info.py
In this pr, I did some small refactorings such as:
- coloring password inputs
- adding one `get_key()` that is reused instead of having 3 implementations
- make sure that the question asking for key name input is the same everywhere
> Small refactoring and reuse one `get_key()` for all commands 

- repository_service_tuf/cli/artifact/add.py
- repository_service_tuf/helpers/cli.py
- tests/unit/cli/artifact/test_add.py
- Fix bug related the giving the RSTUF API Server (``--api-server``)
- Makes the user experience with ``--path`` and `filepaht` simpler and the output, see the cases below
Using a `rstuf.yaml`
```shell
> rstuf -c rstuf.yaml artifact add ~/tuf_metadata.tar
Artifact Addition status: ACCEPTED (94c234877b124bc5a747a9c4e0cb4761)
Successfully submitted task with a payload of:
{
"targets": [
{
"info": {
"length": 106956800,
"hashes": {
"blake2b-256": "597b97e43e445ecd06dfb8436b19e2ae6cfa137dd66523b9a022989355bde3dc"
},
"custom": null
},
"path": "tuf_metadata.tar"
}
],
"add_task_id_to_custom": false,
"publish_targets": true
}
RSTUF task ID (use to check its status) is: 94c234877b124bc5a747a9c4e0cb4761
```
Using the `--path` and `--api-server`
```shell
> rstuf artifact add ~/tuf_metadata.tar …
```
> Fix bugs in `artifact add` and improve UX

- docs/source/guide/index.rst
- repository_service_tuf/__version__.py
- repository_service_tuf/cli/__init__.py
Activating autocompletion requires modifying specific files, something that users might not want to happen by default.
Also, these files might have permissions that don't allow it.
With this PR we make autocomplete activation an option in the `rstuf` command.
> Make autocompletion activation a command

- tox.ini
Original bug reported by @MVrachev:
>  if precommit is not updated to latest versions of linters locally it will fail.
Some context:
> Do we have a GitHub automated pr
Yes, we do have in https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/main/.github%2Fworkflows%2Fupdate-pre-commit-hooks.yml.
> Asking as currently, if precommit is not updated to latest versions of linters locally it will fail.
This should not be happening, it is supposed to only be a [warning message](https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/main/tox.ini). If that's not happening then it's a bug.
> If we have the same automated pr updating the CLI precommit hooks we would be able to remove this requirement.
With the same reasoning we should remove also the …
> fix: Stop tox `precommit` modifying files

- docs/source/guide/index.rst
This change fixes the `import-artifacts` example in the docs, so that it uses `--api-server` instead of the non-existing `--metadata-url` flag. This also partially resolves `import-artifacts` functional tests, which were failing in the CI.
Fixes #456
- [ n/a] Tests have been added for the bug fix or new feature
- [n/a ] Docs have been added for the bug fix or new feature
> Fix `import-artifacts` docs

- Pipfile
- Pipfile.lock
- pyproject.toml
- repository_service_tuf/cli/admin/import_artifacts.py
- repository_service_tuf/cli/admin/metadata.py
- repository_service_tuf/cli/admin2/helpers.py
- repository_service_tuf/helpers/tuf.py
- requirements-dev.txt
- requirements.txt
- tests/conftest.py
- tests/unit/cli/admin/test_import_artifacts.py
- tests/unit/cli/admin/test_metadata.py
- tests/unit/cli/artifact/test_download.py
- tests/unit/cli/test_admin2.py
- tests/unit/helpers/test_tuf.py
- tox.ini
Update python-tuf to version 4.0.0. See release notes here: https://github.com/theupdateframework/python-tuf/blob/v4.0.0/docs/CHANGELOG.md.
The new python-tuf version gives us the required `Root.get_verification_result()` API call which we use
for our new refactoring commands.
The specification defines `datetime` as UTC time zone:
https://theupdateframework.github.io/specification/latest/#file-formats-date-time
The python-tuf project updated all their datetime objects,  so it's time we do it now as well.
Additionally, I updated everywhere to replace `datetime.utc()` to `datetime.now(timezone.utc)`
as `datetime.utc()`  is documented for
deprecation and is officially deprecated from python 12:
https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow
Also, I added to all …
> Update python-tuf to 4.0.0 & remove pinning & update to utc timezone

- tests/conftest.py
- tests/unit/cli/admin/test_import_artifacts.py
- tests/unit/cli/admin_legacy/test_ceremony.py
- tests/unit/cli/admin_legacy/test_metadata.py
- tests/unit/cli/artifact/test_add.py
- tests/unit/cli/artifact/test_download.py
- tests/unit/cli/artifact/test_repository.py
- tests/unit/cli/key/test_generate.py
- tests/unit/cli/task/test_info.py
Fix unit tests caused by internal Python changes:
Subprocesses have changed where exception messages are stored.
From stdout exception messages are moved to stderr and we need to adapt.
Additionally, we use `called_once` for one test for a mock where we
need to migrate to `assert_called_once_with` as for python 12.
called_once is gone: https://github.com/python/cpython/issues/100690
Finally, Fix "ValueError: stderr not separately captured.
This error is given by `subprocess` when we want to access the stderr
of the test_result object returned from `click.invoke`.
This is fixed by using "mix_stderr" on `CliRunner` level.
https://click.palletsprojects.com/en/latest/api/#testing
> Tests: fix UT bugs regarding subprocess & python v12 changes

- .gitignore
- docs/source/guide/index.rst
- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/cli/admin/sign.py
- repository_service_tuf/cli/key/__init__.py
- repository_service_tuf/helpers/api_client.py
- tests/conftest.py
- tests/files/payload/sign_pending_roles.json
- tests/unit/cli/admin/test_ceremony.py
- tests/unit/cli/admin/test_sign.py
- tests/unit/cli/admin/test_update.py
- tests/unit/helpers/test_api_client.py
The changes aim to:
1. fail early if none of 'api-server' or 'SIGNING_JSON_INPUT_FILE' is
provided
2. allow the combination of 'api-server' AND 'SIGNING_JSON_INPUT_FILE'
3. if 'save' is not used and 'api-server' is not provided then save
result at DEFAULT_PATH (sign_payload.json at the moment)
4. simplify the sign helper functions
5. modify the 'tests/files/payload/sign_pending_roles.json' example
payload to follow the actual API response from "GET /api/v1/metadata"
Finally, the changes address some small comments made by @lukpueh in a previous pr
and improve tests.
> Improvements on top of new sign and tests

- repository_service_tuf/cli/admin/helpers.py
- repository_service_tuf/cli/admin/sign.py
- repository_service_tuf/helpers/tuf.py
- tests/conftest.py
- tests/unit/cli/admin/test_ceremony.py
Add:  
- test we cannot add online key as one of root keys
- requirement that threshold > 2 & add test for that
- test that expiration days must be a positive number
Additionally, improve type annotations in a few places
and move ceremony tests input inside conftest to be reused.
Related to #533
> Add tests for ceremony edge cases & improve type annotations

- docs/source/guide/index.rst
- repository_service_tuf/cli/admin/ceremony.py
- repository_service_tuf/cli/admin/sign.py
- tests/unit/cli/admin/test_ceremony.py
- tests/unit/cli/admin/test_sign.py
The '--dry-run' option scope is regarding the command output.
This means that when the option is used it will not influence the
input options.
Instead, it will directly interfere with the output. If '--dry-run'
is used, then the CLI will ignore both '--api-server' admin option
and the RSTUF configuration file and its corresponding SERVER option.
Signed-off-by: Martin Vrachev <martin.vrachev@broadcom.com>
Related to #533.
> Add '--dry-run' option for 'ceremony' and 'sign' commands

- repository_service_tuf/cli/admin/sign.py
- tests/unit/cli/admin/test_sign.py
This commit adds a more user-friendly output when no metadata is available for signing.
"No metadata available for signing"
> fix: explicity output (graceful) when no signing

- docs/source/devel/repository_service_tuf.cli.admin.delegations.rst
- docs/source/devel/repository_service_tuf.cli.admin.metadata.rst
- docs/source/devel/repository_service_tuf.cli.admin.rst
- docs/source/guide/index.rst
- repository_service_tuf/cli/admin/__init__.py
- repository_service_tuf/cli/admin/delegations/new.py
- repository_service_tuf/cli/admin/metadata/sign.py
- repository_service_tuf/helpers/api_client.py
- tests/conftest.py
- tests/unit/cli/admin/test_admin.py
- tests/unit/cli/admin/test_sign.py
- tests/unit/helpers/test_api_client.py
Feature to support sending headers (HTTP) while using rstuf admin command.
RSTUF might be deployed behind a API Gateway or some authentication layer that requires a token or API Key or specific headers.
This feature enables users to pass headers using `--headers/-H` parameter.
This feature can be compared with `curl -H`
It supports headers such as `apikey: somekey,  Content-Type: application/json'` for example.
Examples:
```bash
rstuf admin --api-server http://api.dev.rstuf.org -H 'apikey: mykey' ceremony
```
```bash
rstuf admin --api-server http://api.dev.rstuf.org -H $TOKEN metadata sign
```
Fixes #(issue)
> feat: Support headers for admin `rstuf admin -H`

- repository_service_tuf/cli/admin/helpers.py
- tests/unit/cli/admin/test_helpers.py
- do not crash if user gives a unecrypted key asking for the key again
- fix formatting for loading the private key
Fixes #814 
Fixes #789
> fix: crash uncrypted private key

- repository_service_tuf/cli/admin/helpers.py
- repository_service_tuf/cli/admin/metadata/sign.py
- repository_service_tuf/cli/admin/metadata/stop_sign.py
The preview wasn't work properly for signing or stop signing when the Metadata was a Targets type.
the _print_targets() expected the full metadata and not the signed portion.
Fixes PR #696
> fix: `rstuf admin metadata sign|stop-sign` preview

- repository_service_tuf/cli/task/info.py
- repository_service_tuf/helpers/api_client.py
- tests/unit/cli/task/test_info.py
This feature was also added during KubeCon 2025 in London while demonstrate RSTUF.
Depending of the task you want to see all details.
This commit shows the Task data for more detailed view when using `--all|-a`
> feat: task info all data `rstuf task info --all|-a <task id>`

- repository_service_tuf/cli/admin/helpers.py
- tests/unit/cli/admin/test_helpers.py
headers is not passed to `request_server` which cause error if headers is required to access RSTUF.
> fix: `admin` command fails while using headers

- repository_service_tuf/cli/artifact/delete.py
- repository_service_tuf/cli/artifact/download.py
- repository_service_tuf/cli/artifact/repository.py
- repository_service_tuf/helpers/cli.py
- tests/unit/cli/artifact/test_delete.py
- tests/unit/cli/artifact/test_download.py
- tests/unit/cli/artifact/test_repository.py
- tests/unit/helpers/test_cli.py
This PR came out from KubeCon 2025 in London where we use it during the demos.
I just added some tests and it look good now.
- Fix when users want to use a local trusted file, importing it correctly
- Allow uses to use Root metadata from metadata url as import
- Fix users to download using Trust-on-First-usage (TOFU), by downloading the 1.root.json
- Fix the usage by not requiring the file to exists locally as it doesn't require any information such as hash or size for delete, only the path
> fix and improve `rstuf artifact` command

- .github/workflows/ci.yml
Pinning the GitHub Actions version to a specific commit to follow the repository standard. We are using the [current latest commit from GitHub Actions cache repository](https://github.com/actions/cache/commit/5a3ec84eff668545956fd18022155c47e93e2684) for the pin.
Fixes #652
> Pin GitHub Actions versions cache to specific commit SHA 

- Makefile
help developers/contributors see the supported help commands
```shell
❯ make
Makefile commands:
reformat                       Reformat code with black and isort
tests                          Run all tests
precommit                      Install and run pre-commit hooks
coverage                       Run tests with coverage
docs                           Build documentation
run-dev                        Run the development environment
stop                           Stop the development environment
clean                          Clean up the environment
help                           Show this help message
```
> docs: add `make help`

- docker-compose.yml
Upgrades the docker containers from:
* Postress 15.1 to 17.5
Both have the same vulnerability scores and none of the other images have a lower vulnerability score.
* python 3.12 to 3.13
3.13 image has no identified vulnerabilities until now
* redis 4.0 to 8.0
The 4.0 image had vulnerabilities while the 8.0 doesn't have any vulnerabilities until now.
> Updated docker images
