repository_service_tuf/__init__.py, repository_service_tuf/__version__.py, repository_service_tuf/cli/__init__.py, repository_service_tuf/cli/admin/__init__.py, repository_service_tuf/cli/admin/ceremony.py, repository_service_tuf/cli/admin/login.py, repository_service_tuf/cli/admin/token.py, repository_service_tuf/helpers/__init__.py, repository_service_tuf/helpers/api_client.py, repository_service_tuf/helpers/tuf.py, tests/conftest.py, tests/test_tuf_repository_service.py, tests/tools/generate_keys.py, tests/unit/cli/admin/__init__.py, tests/unit/cli/admin/test_ceremony.py, tests/unit/cli/admin/test_login.py, tests/unit/helpers/__init__.py, tests/unit/helpers/test_api_client.py
Update Copyright to VMware Inc.
=> Update Copyright to VMware Inc

Pipfile.lock, requirements-dev.txt, requirements.txt
This commit update multiple dependencies and closes dependabot PRs.
=> build: Update multiple dependencies

docs/source/guide/index.rst, repository_service_tuf/cli/admin/ceremony.py
Fix the default expiration date typo.
Closes: #88 
=> Fix default expiration date typo

repository_service_tuf/cli/admin/ceremony.py, repository_service_tuf/helpers/tuf.py, tests/conftest.py, tests/unit/cli/admin/test_ceremony.py
Adding Unit Tests for ceremony._key_is_duplicated().
- types added to some of the key-related properties of classes
- corrected logic of the _key_is_duplicated function
- fixed typos
- added UTs
Closes #16
=> Dev/add UT for ceremony._key_is_duplicated

repository_service_tuf/__version__.py
=> Release v0.0.1a4

.gitignore
Add vscode settings to .gitignore.
=> Add vscode settings to .gitignore

Pipfile, Pipfile.lock, pyproject.toml, requirements-dev.txt, requirements.txt, tox.ini
- Removed unnecessary requirements from Pipfile (updated requirements)
- Added necessary requirements when building/installing the package
Fixes #119
=> Fix necessary requirements for the package

.github/workflows/update-python-deps.yml
Fixes the formatting on the dependency workflow. 
Reference - https://github.com/vmware/repository-service-tuf-cli/actions/runs/3346418097
Signed-off-by: Radoslav Dimitrov <dimitrovr@vmware.com>
=> fix: fix the dependency workflow formatting

repository_service_tuf/__version__.py
=> Release v0.0.1a5

repository_service_tuf/__version__.py
=> Release v0.0.1a6

repository_service_tuf/__version__.py
=> Release v0.0.1a7

.pre-commit-config.yaml, Makefile, Pipfile, Pipfile.lock, requirements-dev.txt, requirements.txt
- fix `make requirements`
- remove black as pinned
- update dev dependencies
- update `.pre-commit-config.yaml` aligned to `requirements-dev.txt`
Closes #184 
=> fix `make requirement` and update dev dependencies

repository_service_tuf/__init__.py, repository_service_tuf/__version__.py, repository_service_tuf/cli/__init__.py, repository_service_tuf/cli/admin/__init__.py, repository_service_tuf/cli/admin/ceremony.py, repository_service_tuf/cli/admin/login.py, repository_service_tuf/cli/admin/token.py, repository_service_tuf/helpers/__init__.py, repository_service_tuf/helpers/api_client.py, repository_service_tuf/helpers/tuf.py, tests/conftest.py, tests/test_tuf_repository_service.py, tests/tools/generate_keys.py, tests/unit/cli/admin/__init__.py, tests/unit/cli/admin/test_ceremony.py, tests/unit/cli/admin/test_login.py, tests/unit/helpers/__init__.py, tests/unit/helpers/test_api_client.py
- Bump version
- Update the Copyright
=> Release v0.0.1a8

MAINTAINERS.rst, Pipfile.lock, repository_service_tuf/cli/admin/import_targets.py, requirements-dev.txt, requirements.txt, tests/unit/cli/admin/test_import_targets.py
This PR intends to update the `feature/role-simplification` branch with the latest updates from the main.
=> Update the feature/role-simplification branch

repository_service_tuf/__version__.py
Component Interoperability Matrix
* RSTUF API >= v0.0.2a1
=> Release v0.0.1a9

repository_service_tuf/__version__.py
* Component Interoperability Matrix
- RSTUF API >= v0.1.0a1
=> Release v0.1.0a1

repository_service_tuf/__version__.py
* Component Interoperability Matrix
- RSTUF API >= v0.1.1a1
=> Release v0.1.1a2

.github/workflows/cd.yml
Rename FT organization job dispatcher from `vmware` to `repository-service-tuf`.
=> Rename FT organization job dispatcher

repository_service_tuf/cli/key/generate_key.py, tests/unit/cli/key/test_generate_key.py
=> Add UT for the missing coverage at `generate_key.py`

CONTRIBUTING.rst, Pipfile, pyproject.toml, repository_service_tuf/cli/key/generate_key.py, tox.ini
fixes: #282
1.  doc and pyproject.toml are updated.
2.  match case code are replaced with If conditions
Signed-off-by:  Chirag ( deepNet-Chirag )
=> Python version mismatch #281 Solved

.github/workflows/cd.yml
Add permission to update the release from `-rc`
=> Update cd.yml for release

repository_service_tuf/cli/admin/token.py
=> Change message in exception after package renaming

repository_service_tuf/__version__.py
* Component Interoperability Matrix
- RSTUF API >= v0.3.0b1
=> Release v0.3.0a1

repository_service_tuf/__version__.py
=> Release 0.4.0b1

Pipfile, Pipfile.lock, pyproject.toml, repository_service_tuf/cli/__init__.py, requirements-dev.txt, requirements.txt
Test the CLI: `pip install -e .`
=> Add shell completion automatically to `rstuf`

repository_service_tuf/cli/admin/login.py
Add missing scopes in the latest API endpoints
Closes #365 
=> Add missing scopes added in latest new API endpoints

repository_service_tuf/__version__.py
Prepare release 0.6.0b1
Fixes #(issue)
=> Prepare release 0.6.0b1

Pipfile, Pipfile.lock, pyproject.toml, requirements-dev.txt, requirements.txt
The newest securesystemslib 0.29.0 requires investigation and fix on RSTUF CLI.
It is a workaround for issue #372
related #372
=> fix: securesystemslib 0.28.0 pinned

repository_service_tuf/__version__.py
=> Prepare release v0.6.1b1

repository_service_tuf/cli/admin/ceremony.py, tests/unit/cli/admin/test_ceremony.py
This change outputs a warning and a number of pending root signatures during DAS bootstrap ceremony
Fixes #355
- [n/a ] Docs have been added for the bug fix or new feature
=> Add information about pending signatures

docs/source/devel/index.rst, docs/source/devel/repository_service_tuf.cli.artifact.rst, docs/source/devel/repository_service_tuf.cli.rst, docs/source/devel/repository_service_tuf.helpers.rst, docs/source/guide/index.rst, repository_service_tuf/cli/artifact/__init__.py, repository_service_tuf/cli/artifact/add.py, repository_service_tuf/helpers/api_client.py, repository_service_tuf/helpers/cli.py, tests/unit/cli/artifact/__init__.py, tests/unit/cli/artifact/test_add.py, tests/unit/helpers/test_cli.py
- Tests for the newly added command are still pending, but wanted to push the work so far for review.
- We probably need to redesign the way we authenticate to the API and better define how we want to use the `.rstuf.ini` config file. TBD in another task.
Closes #343
=> Implement `rstuf artifact add` command

repository_service_tuf/__version__.py
Prepare release 0.7.0b1 since the relevant [Milestone](https://github.com/repository-service-tuf/repository-service-tuf-cli/milestone/10?closed=1) has been completed.
=> Prepare release 0.7.0b1

CONTRIBUTING.rst, docs/source/guide/index.rst, repository_service_tuf/cli/key/generate.py, repository_service_tuf/cli/key/info.py, repository_service_tuf/helpers/tuf.py, tests/unit/cli/key/test_generate.py, tests/unit/cli/key/test_info.py
This prints the key information after a new key is generated.
Fixes #353
=> Display new key information

.github/workflows/cd.yml, .github/workflows/functional-tests.yml, .github/workflows/review-approved.yml, .gitignore, Makefile, docker-compose.yml, tox.ini
It adds the new FT workflow.
This workflow is triggered when a PR is approved.
It avoids changes that breaks the consistency and performance with RSTUF deployment.
This FT workflow is used also during the release.
Fixes #(issue)
=> Add workflow for new FT

.github/workflows/functional-tests.yml, .github/workflows/review-approved.yml
Use only the default docker-compose.yml
Call the workflow giving the corret parameters
Fixes #(issue)
=> fix: FT when PR is approved

repository_service_tuf/cli/admin/login.py, repository_service_tuf/helpers/cli.py
Remove non-existing scope "read:metadata" and docs issues.
Fixes #397
=> Fix non-existing scope "read:metadata"

docs/source/devel/repository_service_tuf.cli.rst, docs/source/devel/repository_service_tuf.cli.task.rst, docs/source/guide/index.rst, repository_service_tuf/cli/task/__init__.py, repository_service_tuf/cli/task/info.py, tests/unit/cli/task/test_info.py
=> Add `rstuf task info` command

repository_service_tuf/__version__.py
=> Prepare release v0.8.1b1

repository_service_tuf/cli/admin/ceremony.py, repository_service_tuf/cli/admin/import_artifacts.py, repository_service_tuf/cli/admin/metadata.py, repository_service_tuf/cli/artifact/add.py, repository_service_tuf/helpers/api_client.py, tests/unit/cli/admin/test_ceremony.py, tests/unit/cli/admin/test_import_artifacts.py, tests/unit/cli/admin/test_metadata.py, tests/unit/cli/artifact/test_add.py, tests/unit/helpers/test_api_client.py
=> Renamed enum class variable

docs/source/guide/index.rst
`--api-url` was changed to `--api-server`
Closes #347
=> fix: Update `rstuf admin import-artifacts` docs

repository_service_tuf/__version__.py
=> Prepare release v0.8.2b1

.coveragerc, Pipfile.lock, requirements-dev.txt, requirements.txt, tests/__init__.py, tests/unit/__init__.py, tests/unit/cli/__init__.py, tests/unit/cli/key/__init__.py, tox.ini
Configuration to skip tests in coverage.
Reference https://pytest-cov.readthedocs.io/en/latest/config.html#configuration.
=> Skip tests in coverage

repository_service_tuf/__version__.py
=> Prepare release v0.8.3b1

repository_service_tuf/cli/admin/ceremony.py, repository_service_tuf/helpers/tuf.py, tests/conftest.py
Preparation for bootstrap payload changes done in prs:
- ~API: https://github.com/repository-service-tuf/repository-service-tuf-api/pull/551~ 
- API https://github.com/repository-service-tuf/repository-service-tuf-api/pull/554
- Worker: https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/461
=> Address latest bootstrap payload changes

repository_service_tuf/__version__.py
=> Release v0.10.0b1

repository_service_tuf/__version__.py
=> Release v0.11.0b1

docs/source/guide/index.rst
- Fix subtitle
- Fix subtitle missing anchor
=> Fix docs Artifact CLI

tests/conftest.py, tests/files/das-root.json, tests/files/root.json, tests/unit/cli/admin/test_ceremony.py, tests/unit/cli/admin/test_metadata.py, tests/unit/helpers/test_tuf.py
Bump root md for tests for current admin commands
This is a temporary fix, so our UT tests will not fail.
Signed-off-by: Martin Vrachev <martin.vrachev@broadcom.com>
=> Bump root md for tests for current admin commands

docker-compose.yml
Define the new online key config to be compatible with new FT.
=> fix: Use new online key config for Worker

docs/source/devel/design.rst, docs/source/guide/index.rst, repository_service_tuf/cli/admin_legacy/__init__.py, repository_service_tuf/cli/key/__init__.py
- Add warnings for users using `rstuf admin-legacy` and `rstuf key`
- Update development docs 
- Update guide docs: rstuf.yml config file
- Closes https://github.com/repository-service-tuf/repository-service-tuf-cli/issues/562
=> chore: docs and warnings

repository_service_tuf/__version__.py
=> Release v0.12.0b1

repository_service_tuf/__version__.py
=> release: v0.13.0b1

pyproject.toml, repository_service_tuf/__version__.py
- Fix required dependency for sigstore
Fixes #(issue)
=> hotfix: release v0.13.1b1

repository_service_tuf/__version__.py
=> release: v0.14.0b1

.github/workflows/functional-tests.yml
CLI cannot affect the performance.
The performance is on processing the metadata, in RSTUF it is done by the Worker
Fixes #(issue)
=> test: remove FT slow from CLI

repository_service_tuf/cli/admin/helpers.py, repository_service_tuf/cli/admin/sign.py, tests/conftest.py, tests/unit/cli/admin/test_helpers.py
Add threshold info, highlighs and info sentences.
=> Add threshold info, highlighs and info sentences

.gitignore, docker-compose.yml, repository_service_tuf/cli/admin/ceremony.py, repository_service_tuf/cli/admin/delegations/__init__.py, repository_service_tuf/cli/admin/delegations/delete.py, repository_service_tuf/cli/admin/delegations/new.py, repository_service_tuf/cli/admin/helpers.py, repository_service_tuf/cli/admin/metadata/__init__.py, repository_service_tuf/cli/admin/metadata/sign.py, repository_service_tuf/cli/admin/metadata/update.py, repository_service_tuf/helpers/api_client.py, tests/conftest.py, tests/files/payload/ceremony.json, tests/unit/cli/admin/test_ceremony.py, tests/unit/cli/admin/test_helpers.py, tests/unit/cli/admin/test_sign.py, tests/unit/cli/admin/test_update.py
Add a feature to a user as admin to use Custom Delegations
TODO:
=> feat: Custom Delegation roles command line

docker-compose.yml
build: rename RSTUF_SQL_SERVER -> RSTUF_DB_SERVER in Worker
=> build: rename RSTUF_SQL_SERVER -> RSTUF_DB_SERVER in Worker

repository_service_tuf/cli/admin/helpers.py, tests/unit/cli/admin/test_helpers.py
Added Email validation for sigstore identity. It will validate whether the identity input by user is email or not
Fixes #671 
=> fix: Email Validation for SigStore identity

repository_service_tuf/__version__.py
=> Prepare release v0.15.1b1

repository_service_tuf/__version__.py
=> release: v0.16.0b1

repository_service_tuf/__version__.py
=> release: v0.17.0b1

repository_service_tuf/__version__.py
=> release: v0.17.1b1

.github/workflows/ci.yml, .readthedocs.yaml, CONTRIBUTING.rst, Pipfile, Pipfile.lock, docker-compose.yml, pyproject.toml, tox.ini
Update python versions: 
- add python 3.13
- remove incosistent 3.9 from tox.ini
=> Update python versions: add python 3.13, remove incosistent 3.9 from tox.ini

.github/dependabot.yml
Enable dependabot for Python packages
=> build: enable dependabot for python packages

docs/source/devel/repository_service_tuf.cli.admin.delegations.rst, docs/source/devel/repository_service_tuf.cli.admin.metadata.rst, docs/source/devel/repository_service_tuf.cli.admin.rst, docs/source/devel/repository_service_tuf.cli.admin.send.rst, docs/source/devel/repository_service_tuf.cli.artifact.rst, docs/source/devel/repository_service_tuf.cli.rst, docs/source/devel/repository_service_tuf.cli.task.rst, docs/source/devel/repository_service_tuf.helpers.rst, docs/source/devel/repository_service_tuf.rst, repository_service_tuf/__version__.py
=> Release v1.0.0b1

repository_service_tuf/cli/admin/import_artifacts.py
Resolve incorrect csv parsing
Replaces plain reading of csv files with csv reader as recommended in the security document
Fixes #813 
=> Resolve incorrect parsing of CSV Files

MAINTAINERS.rst
=> Update maintainers emails

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/functional-tests.yml, .github/workflows/review-approved.yml, .github/workflows/update-pre-commit-hooks.yml
This PR addresses security findings from Scorecard regarding GitHub workflow token permissions. It implements the principle of least privilege by explicitly defining minimal required permissions in all workflow files.
Specific changes:
- Added explicit top-level permissions to workflows where they were missing
- Added appropriate comments documenting why each permission is needed
- Ensured all workflows follow permission best practices
Fixes #653 
By submitting this PR, you agree to follow our Code of Conduct.
=> Reduce the GitHub workflow tokens' permissions
